name: Decomp.dev progress report
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Upload progress report
        uses: actions/upload-artifact@v4
        with:
          name: SLPM_654.95_report
          path: tools/report.json
